services:
  - type: web
    name: art-house-cpsoft
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 30 "server:create_app()"
    healthCheckPath: /healthz
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_ORIGIN
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: Art House
