-- Art House schema for Supabase PostgreSQL.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    salt TEXT NOT NULL,
    password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS registered_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type TEXT NOT NULL DEFAULT 'user' CHECK (account_type IN ('user', 'seller')),
    created_at BIGINT NOT NULL DEFAULT ((extract(epoch FROM clock_timestamp()) * 1000)::bigint)
);
CREATE TABLE IF NOT EXISTS account_credentials (
    account_id BIGINT PRIMARY KEY REFERENCES registered_accounts(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_salt TEXT NOT NULL,
    password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sellers (
    id BIGINT PRIMARY KEY REFERENCES registered_accounts(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    bio TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT ((extract(epoch FROM clock_timestamp()) * 1000)::bigint)
);
CREATE TABLE IF NOT EXISTS listed_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES sellers(id),
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price_cents BIGINT NOT NULL CHECK (price_cents >= 0),
    inventory INTEGER NOT NULL DEFAULT 0 CHECK (inventory >= 0),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'archived')),
    created_at BIGINT NOT NULL DEFAULT ((extract(epoch FROM clock_timestamp()) * 1000)::bigint)
);
CREATE TABLE IF NOT EXISTS checkouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL REFERENCES registered_accounts(id),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled', 'refunded')),
    total_cents BIGINT NOT NULL CHECK (total_cents >= 0),
    created_at BIGINT NOT NULL DEFAULT ((extract(epoch FROM clock_timestamp()) * 1000)::bigint)
);
CREATE TABLE IF NOT EXISTS checkout_items (
    checkout_id BIGINT NOT NULL REFERENCES checkouts(id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES listed_items(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_cents BIGINT NOT NULL CHECK (unit_price_cents >= 0),
    PRIMARY KEY (checkout_id, item_id)
);
CREATE TABLE IF NOT EXISTS login_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES registered_accounts(id) ON DELETE SET NULL,
    email TEXT NOT NULL,
    succeeded INTEGER NOT NULL CHECK (succeeded IN (0, 1)),
    created_at BIGINT NOT NULL DEFAULT ((extract(epoch FROM clock_timestamp()) * 1000)::bigint)
);
CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS attempts (
    key TEXT PRIMARY KEY,
    count INTEGER NOT NULL,
    expires BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS password_reset_codes (
    email TEXT PRIMARY KEY,
    code_hash TEXT NOT NULL,
    expires BIGINT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);
